"""
SFT Data Preparation Pipeline

Label-masking strategy
-----------------------
Input tokens  (system prompt + user turn)  → label = IGNORE_INDEX (-100)
Output tokens (assistant response)         → label = token id
Loss is computed ONLY on response tokens, never on the prompt.

  train_tokens.bin   - uint32 token ids,  shape (N_train,)
  train_labels.bin   - int32  label ids,  shape (N_train,)   -100 = masked
  val_tokens.bin     - uint32 token ids,  shape (N_val,)
  val_labels.bin     - int32  label ids,  shape (N_val,)
  val_examples.jsonl - human-readable held-out examples for inference testing
                     - one JSON object per line:
                     -   {"prompt": str, "response": str, "source": str}
  metadata.json      - statistics + config snapshot
"""

import os
import json
import random
import argparse
import re
import numpy as np
import tiktoken
from tqdm import tqdm
from datasets import load_dataset

# constants
IGNORE_INDEX = -100          # positions masked from loss
EOT_TOKEN    = None          # resolved at runtime from tiktoken enc.eot_token
END_TOKEN_STR = "\n### END"

#Alpaca-style prompt templates
'''
ALPACA_WITH_INPUT = (
    "### Instruction:\n{instruction}\n\n"
    "### Input:\n{input}\n\n"
    "### Response:\n"
)
'''

ALPACA_WITH_INPUT = (
    "### SYSTEM:\n{input}\n\n"
    "### Instruction:\n{instruction}\n\n"
    "### Response:\n"
)

ALPACA_NO_INPUT = (
    "### Instruction:\n{instruction}\n\n"
    "### Response:\n"
)


def load_alpaca(cache_dir: str) -> list[dict]:
    """tatsu-lab/alpaca  –  52 k single-turn instruction examples."""
    ds = load_dataset("tatsu-lab/alpaca", split="train", cache_dir=cache_dir)
    out = []
    for ex in ds:
        instruction = ex.get("instruction", "").strip()
        inp         = ex.get("input", "").strip()
        response    = ex.get("output", "").strip()
        if not instruction or not response:
            continue
        prompt = ALPACA_WITH_INPUT.format(instruction=instruction, input=inp) \
                 if inp else ALPACA_NO_INPUT.format(instruction=instruction)
        out.append({"prompt": prompt, "response": response})
    return out


def load_dolly(cache_dir: str) -> list[dict]:
    """databricks/databricks-dolly-15k  –  15 k human-written instructions."""
    ds = load_dataset("databricks/databricks-dolly-15k", split="train",
                      cache_dir=cache_dir)
    out = []
    for ex in ds:
        instruction = ex.get("instruction", "").strip()
        context     = ex.get("context", "").strip()
        response    = ex.get("response", "").strip()
        if not instruction or not response:
            continue
        prompt = ALPACA_WITH_INPUT.format(instruction=instruction, input=context) \
                 if context else ALPACA_NO_INPUT.format(instruction=instruction)
        out.append({"prompt": prompt, "response": response})
    return out

def load_evol_instruct(cache_dir: str) -> list[dict]:
    """
    WizardLM/WizardLM_evol_instruct_V2_196k
    Complex, evolved instructions – single-turn.
    """
    ds = load_dataset(
        #"sft_data/hf_cache/WizardLM___wizard_lm_evol_instruct_v2_196k",
        "WizardLM/WizardLM_evol_instruct_V2_196k",
        split="train",
        cache_dir=cache_dir,
        
    )
    out = []
    set_instructions = f"You are a helpful AI Assistant. Below is an instruction that describes a task. Write a detailed, accurate and concise response that appropriately completes the request"
    #f"You are a helpful AI assistant who follows the given instructions and provides a detailed, accurate and concise answers."
    for ex in ds:
        # Dataset has 'conversations' list with human/gpt turns
        conversations = ex.get("conversations", [])
        if len(conversations) < 2:
            continue
        human_turn = conversations[0]
        gpt_turn   = conversations[1]
        if human_turn.get("from", "").lower() not in ("human", "user"):
            continue
        if gpt_turn.get("from", "").lower() not in ("gpt", "assistant"):
            continue
        instruction = human_turn.get("value", "").strip()
        response    = gpt_turn.get("value", "").strip()
        if not instruction or not response:
            continue
        prompt = ALPACA_WITH_INPUT.format(instruction=instruction, input=set_instructions)
        out.append({"prompt": prompt, "response": response})
    return out


def load_everyday_conversations(cache_dir: str) -> list[dict]:
    """
    HuggingFaceTB/everyday-conversations-llama3.1-2k
    Short, natural everyday dialogues (~2 k conversations) generated by
    Llama-3.1.  Good for teaching casual conversational tone.

    """
    ds = load_dataset(
        "HuggingFaceTB/everyday-conversations-llama3.1-2k",
        split="train_sft",
        cache_dir=cache_dir,
    )
    out = []
    for ex in ds:
        messages = ex.get("messages", [])
        if not messages:
            continue

        history = ""
        #set_instructions = f"You are a helpful AI assistant who gives a brief, clear and concise answers."
        set_instructions = f"You are an AI assistant who provides simple and easy to understand answers to casual user queries"
        idx = 2  # first pair of conversatoin is always user-> "Hi"/"Hey" assistant-> "Hello, How can I help you?" so not useful
        if len(messages) <= 1:
            continue
        else:
            if messages[idx].get("role") == "user":
                prompt = ALPACA_WITH_INPUT.format(instruction=messages[idx].get("content", ""), input=set_instructions)
                response = messages[idx+1].get("content", "")
            elif messages[idx].get("role") == "assistant":
                prompt = ALPACA_WITH_INPUT.format(instruction=messages[idx+1].get("content", ""), input=set_instructions)
                response = messages[idx+2].get("content", "")
            else:
                continue
            out.append({"prompt": prompt, "response": response})
    return out


def load_gsm8k(cache_dir: str) -> list[dict]:
    """
    openai/gsm8k  (main config, train split)
    
    """
    ds = load_dataset(
        "openai/gsm8k",
        "main",          # config name required by this dataset
        split="train",
        cache_dir=cache_dir,
    )
    out = []
    set_instructions = f"You are an AI assistant who is an expert at solving math problems. Solve the given math word problem step by step using the given instructions"
    for ex in ds:
        question = ex.get("question", "").strip()
        answer   = ex.get("answer",   "").strip()
        if not question or not answer:
            continue
        # Explicit CoT instruction so the model learns to show its work
        
        prompt = ALPACA_WITH_INPUT.format(instruction=question, input=set_instructions)
        out.append({"prompt": prompt, "response": answer})
    return out

def load_orca_math(cache_dir: str) -> list[dict]:
    """
    
    microsoft/orca-math-word-problems-200k  (main config, train split)

    """
    ds = load_dataset(
        "microsoft/orca-math-word-problems-200k",
        split="train",
        cache_dir=cache_dir,
    )
    out = []
    set_instructions = f"You are an AI assistant who is an expert at solving math problems. Solve the given math word problem step by step using the given instructions"
    for ex in ds:
        question = ex.get("question", "").strip()
        answer   = ex.get("answer",   "").strip()
        if not question or not answer:
            continue
        # Explicit CoT instruction so the model learns to show its work
        prompt = ALPACA_WITH_INPUT.format(instruction=question, input=set_instructions)
        out.append({"prompt": prompt, "response": answer})
    return out
    

def load_code_python(cache_dir: str) -> list[dict]:
    """
    flytech/python-codes-25k
    
    """
    ds = load_dataset(
        "flytech/python-codes-25k",
        split="train",
        cache_dir=cache_dir,
    )
    out = []
    set_instructions = f"You are an expert at Python programming. Provide a concise and accurate solution to the following Python coding problem."
    for ex in ds:
        instruction = ex.get("instruction", "").strip()
        response    = ex.get("input", "").strip() + "\n" + ex.get("output", "").strip()
        if not instruction or not response:
            continue
        prompt = (
            ALPACA_WITH_INPUT.format(instruction=instruction, input=set_instructions)
        )
        out.append({"prompt": prompt, "response": response})
    return out


def load_smollm_basics(cache_dir: str) -> list[dict]:
    """
    HuggingFaceTB/instruct-data-basics-smollm-H4
    
    """
    ds = load_dataset(
        "HuggingFaceTB/instruct-data-basics-smollm-H4",
        split="train_sft",
        cache_dir=cache_dir,
    )
    p_hf    = re.compile(r"Hugging\s*Face", re.IGNORECASE)
    p_smol  = re.compile(r"SmolLM",         re.IGNORECASE)
    set_instructions = f"You are a friendly assistant who responds with a casual yet short and simple greet. If instructed, introduce yourself and respond about your identity"
    out = []
    for ex in ds:
        messages = ex.get("messages", [])
        # Find the first user turn and the assistant turn immediately after it
        if not messages:
            continue
        user_content = ex.get("instruction", "").strip()
        asst_content = ex.get("response", "").strip()
        if asst_content == "":
            continue
        user_content = p_smol.sub("customLM",  p_hf.sub("unknownuser", user_content))
        asst_content = p_smol.sub("customLM",  p_hf.sub("unknownuser", asst_content))
        
        prompt = (
            ALPACA_WITH_INPUT.format(instruction=user_content, input=set_instructions)
        )
        out.append({
            "prompt": prompt,
            "response": asst_content,
        })
    return out

def load_smoltalk_filtered(cache_dir: str) -> list[dict]:
    """
    enPurified/smoltalk-creative-writing-enPurified-openai-messages — ~10k filtered conversations from SmolLM's training data.
    """
    ds = load_dataset("enPurified/smoltalk-creative-writing-enPurified-openai-messages", split="train", cache_dir=cache_dir)
    set_instructions = f"You are an instruction-following creative AI Assistant. Below is an instruction that describes a task. Write a response that appropriately completes the request"
    out = []
    for ex in ds:
        messages = ex.get("messages", [])
        prompt = ""
        asst_content = ""
        user_content = ""
        if len(messages) < 2:
            continue
        if messages[0]["role"] == "user" and messages[1]["role"] == "assistant":
            user_content = messages[0]["content"]
            asst_content = messages[1]["content"]
            prompt = ALPACA_WITH_INPUT.format(instruction=user_content, input=set_instructions) # no input form
        elif messages[0]["role"] == "system":
            user_content = messages[1]["content"]
            asst_content = messages[2]["content"]
            user_content = messages[0]["content"] + "\n" + user_content # system + user content
            prompt = ALPACA_WITH_INPUT.format(instruction=user_content, input=set_instructions) # with input form
        else:
            continue
        out.append({
            "prompt": prompt,
            "response": asst_content,
        })
    return out

DATASET_LOADERS = {
    "alpaca":                 load_alpaca,
    "dolly":                  load_dolly,
    "evol_instruct":          load_evol_instruct,
    "everyday_conversations": load_everyday_conversations,
    "gsm8k":                  load_gsm8k,
    "code_python":            load_code_python,
    "smollm_basics":          load_smollm_basics,
    "orca_math":            load_orca_math,
    "smoltalk_10k":           load_smoltalk_filtered
}


def tokenise_and_mask(
    example: dict,
    enc: tiktoken.Encoding,
    max_seq_length: int,
    prompt_mask_fraction=0.5,
) -> tuple[list[int], list[int]] | None:
    """
    Tokenise a single (prompt, response) pair and return
      tokens : list[int]  full token sequence (prompt + response + EOT)
      labels : list[int]  -100 for prompt tokens, token_id for response tokens

    Returns None if the sequence is empty or exceeds max_seq_length.
    """
    prompt_tokens   = enc.encode_ordinary(example["prompt"])
    response_tokens = enc.encode_ordinary(example["response"])
    end_tokens      = enc.encode_ordinary(END_TOKEN_STR)
    eot             = [enc.eot_token]

    tokens = prompt_tokens + response_tokens + end_tokens + eot

    if len(tokens) > max_seq_length:
        # Hard-truncate: keep as many response tokens as possible
        # Always preserve at least 1 response token + EOT
        max_prompt_tokens = int(max_seq_length * prompt_mask_fraction)
        prompt_tokens     = prompt_tokens[:max_prompt_tokens]
        # Reserve space for end_tokens + eot
        remaining         = max_seq_length - len(prompt_tokens) - len(end_tokens) - 1
        response_tokens   = response_tokens[:remaining]
        tokens            = prompt_tokens + response_tokens + end_tokens + eot

    if len(tokens) < 2:
        return None

    # Labels: mask the prompt, supervise the response + EOT
    labels = (
        [IGNORE_INDEX] * len(prompt_tokens)
        + response_tokens
        + end_tokens
        + eot
    )

    assert len(tokens) == len(labels), \
        f"Token/label length mismatch: {len(tokens)} vs {len(labels)}"

    return tokens, labels

def build_mixed_dataset(
    dataset_mix: dict[str, int],
    cache_dir: str,
) -> tuple[list[dict], dict[str, list[dict]], dict[str, int]]:
    """
    Load each dataset and take exactly the number of examples specified by
    dataset_mix (integer counts, not ratios).  Each count is capped at the
    dataset's actual size so the config never needs to be updated when a
    dataset grows or shrinks.

    Parameters
    ----------
    dataset_mix : dict mapping dataset name → desired example count (int)
    cache_dir   : HuggingFace download cache directory

    Returns
    -------
    combined     : shuffled list of all sampled examples
    raw_datasets : dict name → full (unsampled) list for that dataset
                   used by write_eval_jsonl to draw held-out examples
    counts       : dict name → number of examples actually sampled
                   used by write_eval_jsonl to avoid overlap with training
    """
    raw_datasets: dict[str, list[dict]] = {}
    for name, requested in dataset_mix.items():
        if requested <= 0:
            continue
        if name not in DATASET_LOADERS:
            print(f"[WARN] Unknown dataset '{name}', skipping.")
            continue
        print(f"  Loading {name} …")
        raw_datasets[name] = DATASET_LOADERS[name](cache_dir)
        print(f"    → {len(raw_datasets[name]):,} examples available")

    if not raw_datasets:
        raise ValueError("No datasets were loaded. Check dataset_mix in config.")

    counts: dict[str, int] = {}
    for name, data in raw_datasets.items():
        requested = dataset_mix[name]
        counts[name] = min(requested, len(data))
        if counts[name] < requested:
            print(
                f"  [WARN] {name}: requested {requested:,} but only "
                f"{len(data):,} available — using all {len(data):,}."
            )

    combined = []
    for name, data in raw_datasets.items():
        n = counts[name]
        # Take from the HEAD so the TAIL remains a clean held-out pool
        # for write_eval_jsonl
        combined.extend(data[:n])
        print(f"  Sampled {n:,} / {len(data):,} from {name}")

    random.shuffle(combined)
    print(f"  Total combined examples: {len(combined):,}")
    return combined, raw_datasets, counts


# Binary serialisation helpers


def write_bin(path: str, token_list: list[int], dtype: np.dtype) -> None:
    """Write a flat list of integers to a memory-mapped binary file."""
    arr = np.array(token_list, dtype=dtype)
    fp  = np.memmap(path, dtype=dtype, mode="w+", shape=(len(arr),))
    fp[:] = arr
    fp.flush()


def write_eval_jsonl(
    path: str,
    raw_datasets: dict[str, list[dict]],
    counts_per_dataset: dict[str, int],
    n_per_dataset: int = 25,
    seed: int = 42,
) -> int:
    """

    Each line is a JSON object:
        {"prompt": str, "response": str, "source": str}

    Parameters
    ----------
    path               : output file path  (e.g. ./sft_data/val_examples.jsonl)
    raw_datasets       : dict name → full list of examples for that dataset
    counts_per_dataset : dict name → how many examples were used for training
                         (we sample from beyond this index)
    n_per_dataset      : how many held-out examples to keep per dataset
    seed               : random seed for reproducibility

    Returns
    -------
    total number of examples written
    """
    rng = random.Random(seed)
    records: list[dict] = []

    for name, data in raw_datasets.items():
        used = counts_per_dataset.get(name, len(data))
        # Held-out pool = everything NOT used for training
        held_out = data[used:]

        if not held_out:
            # Dataset was fully consumed — fall back to sampling from the
            # training portion (still useful for qualitative checks)
            held_out = data

        n      = min(n_per_dataset, len(held_out))
        sample = rng.sample(held_out, n)

        for ex in sample:
            records.append({
                "prompt":   ex["prompt"],
                "response": ex["response"],
                "source":   name,
            })

    # Shuffle so the JSONL isn't grouped by dataset
    rng.shuffle(records)

    with open(path, "w", encoding="utf-8") as f:
        for rec in records:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")

    return len(records)



# Data Prep


def prepare(config_path: str = "sft_config.json", seed: int = 42) -> None:
    random.seed(seed)
    np.random.seed(seed)

    with open(config_path) as f:
        cfg = json.load(f)

    data_cfg    = cfg["data_config"]
    data_dir    = data_cfg["data_dir"]
    max_seq     = data_cfg["max_seq_length"]
    train_frac  = data_cfg["train_split"]
    dataset_mix = data_cfg["dataset_mix"]
    cache_dir   = os.path.join(data_dir, "hf_cache")
    # Number of held-out examples per dataset written to val_examples.jsonl
    n_eval_per_dataset = data_cfg.get("n_eval_examples_per_dataset", 25)

    os.makedirs(data_dir,  exist_ok=True)
    os.makedirs(cache_dir, exist_ok=True)

    
    enc = tiktoken.get_encoding("gpt2")
    print(f"Tokeniser: gpt2  |  vocab size: {enc.n_vocab}  |  EOT: {enc.eot_token}")

    
    print("\n[1/5] Loading and mixing datasets …")
    examples, raw_datasets, train_counts = build_mixed_dataset(dataset_mix, cache_dir)

    print("\n[2/5] Writing held-out eval examples …")
    eval_jsonl_path = os.path.join(data_dir, "val_examples.jsonl")
    n_eval_written  = write_eval_jsonl(
        path               = eval_jsonl_path,
        raw_datasets       = raw_datasets,
        counts_per_dataset = train_counts,
        n_per_dataset      = n_eval_per_dataset,
        seed               = seed,
    )
    print(f"  Wrote {n_eval_written:,} eval examples → {eval_jsonl_path}")
    print(f"  ({n_eval_per_dataset} per dataset × {len(raw_datasets)} datasets)")

    # ── tokenise + mask ───────────────────────────────────────────────────────
    print(f"\n[3/5] Tokenising {len(examples):,} examples (max_seq={max_seq}) …")
    all_tokens: list[int] = []
    all_labels: list[int] = []
    skipped = 0

    for ex in tqdm(examples, desc="Tokenising"):
        result = tokenise_and_mask(ex, enc, max_seq, prompt_mask_fraction=data_cfg["prompt_mask_fraction"])
        if result is None:
            skipped += 1
            continue
        tokens, labels = result
        all_tokens.extend(tokens)
        all_labels.extend(labels)

    print(f"  Total tokens : {len(all_tokens):,}")
    print(f"  Skipped      : {skipped:,}")


    print(f"\n[4/5] Splitting into train ({train_frac*100:.0f}%) / val …")
    split_idx    = int(len(all_tokens) * train_frac)
    train_tokens = all_tokens[:split_idx]
    train_labels = all_labels[:split_idx]
    val_tokens   = all_tokens[split_idx:]
    val_labels   = all_labels[split_idx:]

    print(f"  Train tokens : {len(train_tokens):,}")
    print(f"  Val   tokens : {len(val_tokens):,}")


    print("\n[5/5] Writing binary files …")
    data_dtype = np.int32
    write_bin(os.path.join(data_dir, "train_tokens.bin"), train_tokens, data_dtype)
    write_bin(os.path.join(data_dir, "train_labels.bin"), train_labels, data_dtype)
    write_bin(os.path.join(data_dir, "val_tokens.bin"),   val_tokens,   data_dtype)
    write_bin(os.path.join(data_dir, "val_labels.bin"),   val_labels,   data_dtype)


    train_supervised = int(np.sum(np.array(train_labels, dtype=data_dtype) != IGNORE_INDEX))
    val_supervised   = int(np.sum(np.array(val_labels,   dtype=data_dtype) != IGNORE_INDEX))

    metadata = {
        "dataset_mix":             dataset_mix,
        "total_examples":          len(examples),
        "skipped_examples":        skipped,
        "train_tokens":            len(train_tokens),
        "val_tokens":              len(val_tokens),
        "train_supervised_tokens": train_supervised,
        "val_supervised_tokens":   val_supervised,
        "eval_jsonl_examples":     n_eval_written,
        "prompt_mask_fraction": round(
            1.0 - train_supervised / max(len(train_tokens), 1), 4
        ),
        "max_seq_length":          max_seq,
        "tokenizer":               "gpt2",
        "ignore_index":            IGNORE_INDEX,
        "config_snapshot":         cfg,
    }
    with open(os.path.join(data_dir, "metadata.json"), "w") as f:
        json.dump(metadata, f, indent=2)

    print("\n✓ Data preparation complete.")
    print(f"  Files written to        : {os.path.abspath(data_dir)}")
    print(f"  Train supervised tokens : {train_supervised:,}  "
          f"({train_supervised/max(len(train_tokens),1)*100:.1f}% of total)")
    print(f"  Val   supervised tokens : {val_supervised:,}")
    print(f"  Eval JSONL examples     : {n_eval_written:,}  ({eval_jsonl_path})")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Prepare SFT data")
    parser.add_argument(
        "--config", default="sft_config.json",
        help="Path to sft_config.json (default: sft_config.json)"
    )
    parser.add_argument(
        "--seed", type=int, default=42,
        help="Random seed for reproducible mixing (default: 42)"
    )
    args = parser.parse_args()
    prepare(config_path=args.config, seed=args.seed)
